# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWin(object):
    def setupUi(self, MWin):
        MWin.setObjectName("MWin")
        MWin.resize(475, 500)
        MWin.setMinimumSize(QtCore.QSize(475, 480))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        MWin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/wordcloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWin.setWindowIcon(icon)
        MWin.setIconSize(QtCore.QSize(30, 30))
        self.centralWidget = QtWidgets.QWidget(MWin)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.centralWidget.setFont(font)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.groupBox)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.text_label = QtWidgets.QLabel(self.frame_5)
        self.text_label.setMinimumSize(QtCore.QSize(30, 30))
        self.text_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.text_label.setObjectName("text_label")
        self.horizontalLayout_2.addWidget(self.text_label)
        self.text_btn = QtWidgets.QToolButton(self.frame_5)
        self.text_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.text_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.text_btn.setObjectName("text_btn")
        self.horizontalLayout_2.addWidget(self.text_btn)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.stop_label = QtWidgets.QLabel(self.frame_4)
        self.stop_label.setMinimumSize(QtCore.QSize(30, 30))
        self.stop_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stop_label.setObjectName("stop_label")
        self.horizontalLayout_3.addWidget(self.stop_label)
        self.stop_btn = QtWidgets.QToolButton(self.frame_4)
        self.stop_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.stop_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_3.addWidget(self.stop_btn)
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMinimumSize(QtCore.QSize(140, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.color_label = QtWidgets.QLabel(self.frame_3)
        self.color_label.setMinimumSize(QtCore.QSize(28, 28))
        self.color_label.setStyleSheet("background:#fff")
        self.color_label.setText("")
        self.color_label.setObjectName("color_label")
        self.horizontalLayout_4.addWidget(self.color_label)
        self.color_btn = QtWidgets.QToolButton(self.frame_3)
        self.color_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.color_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_btn.setStyleSheet("")
        self.color_btn.setObjectName("color_btn")
        self.horizontalLayout_4.addWidget(self.color_btn)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setMinimumSize(QtCore.QSize(140, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.bgi_label = QtWidgets.QLabel(self.frame_2)
        self.bgi_label.setMinimumSize(QtCore.QSize(115, 30))
        self.bgi_label.setMaximumSize(QtCore.QSize(115, 16777215))
        self.bgi_label.setStyleSheet("")
        self.bgi_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bgi_label.setObjectName("bgi_label")
        self.horizontalLayout_5.addWidget(self.bgi_label)
        self.bgi_btn = QtWidgets.QToolButton(self.frame_2)
        self.bgi_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.bgi_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bgi_btn.setStyleSheet("")
        self.bgi_btn.setObjectName("bgi_btn")
        self.horizontalLayout_5.addWidget(self.bgi_btn)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMinimumSize(QtCore.QSize(140, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.font_label = QtWidgets.QLabel(self.frame)
        self.font_label.setMinimumSize(QtCore.QSize(180, 30))
        self.font_label.setMaximumSize(QtCore.QSize(115, 16777215))
        self.font_label.setStyleSheet("")
        self.font_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.font_label.setObjectName("font_label")
        self.horizontalLayout_6.addWidget(self.font_label)
        self.font_btn = QtWidgets.QToolButton(self.frame)
        self.font_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.font_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.font_btn.setStyleSheet("")
        self.font_btn.setObjectName("font_btn")
        self.horizontalLayout_6.addWidget(self.font_btn)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.start_btn = QtWidgets.QToolButton(self.groupBox_3)
        self.start_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.start_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.open_btn = QtWidgets.QToolButton(self.groupBox_3)
        self.open_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.open_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout.addWidget(self.open_btn)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        MWin.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MWin)
        self.statusBar.setObjectName("statusBar")
        MWin.setStatusBar(self.statusBar)

        self.retranslateUi(MWin)
        QtCore.QMetaObject.connectSlotsByName(MWin)

    def retranslateUi(self, MWin):
        _translate = QtCore.QCoreApplication.translate
        MWin.setWindowTitle(_translate("MWin", "词云图生成器"))
        self.groupBox.setTitle(_translate("MWin", "Words"))
        self.label.setText(_translate("MWin", "input text: "))
        self.text_label.setText(_translate("MWin", "null"))
        self.text_btn.setText(_translate("MWin", "..."))
        self.label_2.setText(_translate("MWin", "stop words: "))
        self.stop_label.setText(_translate("MWin", "stopwords.txt"))
        self.stop_btn.setText(_translate("MWin", "..."))
        self.groupBox_2.setTitle(_translate("MWin", "Style"))
        self.label_3.setText(_translate("MWin", "background color: "))
        self.color_btn.setText(_translate("MWin", "..."))
        self.label_4.setText(_translate("MWin", "background image: "))
        self.bgi_label.setText(_translate("MWin", "null"))
        self.bgi_btn.setText(_translate("MWin", "..."))
        self.label_6.setText(_translate("MWin", "fonts:"))
        self.font_label.setText(_translate("MWin", "SourceHanSansCN-Bold"))
        self.font_btn.setText(_translate("MWin", "..."))
        self.groupBox_3.setTitle(_translate("MWin", "Buttons"))
        self.start_btn.setText(_translate("MWin", "Start"))
        self.start_btn.setShortcut(_translate("MWin", "Ctrl+Return"))
        self.open_btn.setText(_translate("MWin", "Open"))
        self.open_btn.setShortcut(_translate("MWin", "Ctrl+O"))
        self.groupBox_4.setTitle(_translate("MWin", "Bugs Feedback"))
        self.label_5.setText(_translate("MWin", "<html><head/><body><p>GitHub：<a href=\"https://github.com/LewisTian/PyQt5-Apps\"><span style=\" text-decoration: underline; color:#0000ff;\">github.com/LewisTian/PyQt5-Apps</span></a></p></body></html>"))

import res_rc
