# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwin.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWin(object):
    def setupUi(self, MWin):
        MWin.setObjectName("MWin")
        MWin.resize(700, 450)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        MWin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWin.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MWin)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout3 = QtWidgets.QVBoxLayout()
        self.layout3.setSpacing(6)
        self.layout3.setObjectName("layout3")
        self.layout1 = QtWidgets.QHBoxLayout()
        self.layout1.setSpacing(6)
        self.layout1.setObjectName("layout1")
        self.input_origin_label = QtWidgets.QLabel(self.centralWidget)
        self.input_origin_label.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_origin_label.setFont(font)
        self.input_origin_label.setObjectName("input_origin_label")
        self.layout1.addWidget(self.input_origin_label)
        self.input_origin = QtWidgets.QLineEdit(self.centralWidget)
        self.input_origin.setObjectName("input_origin")
        self.layout1.addWidget(self.input_origin)
        self.insert = QtWidgets.QPushButton(self.centralWidget)
        self.insert.setObjectName("insert")
        self.layout1.addWidget(self.insert)
        self.query = QtWidgets.QPushButton(self.centralWidget)
        self.query.setObjectName("query")
        self.layout1.addWidget(self.query)
        self.layout3.addLayout(self.layout1)
        self.layout2 = QtWidgets.QHBoxLayout()
        self.layout2.setSpacing(6)
        self.layout2.setObjectName("layout2")
        self.input_trans_label = QtWidgets.QLabel(self.centralWidget)
        self.input_trans_label.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.input_trans_label.setFont(font)
        self.input_trans_label.setObjectName("input_trans_label")
        self.layout2.addWidget(self.input_trans_label)
        self.input_trans = QtWidgets.QLineEdit(self.centralWidget)
        self.input_trans.setText("")
        self.input_trans.setObjectName("input_trans")
        self.layout2.addWidget(self.input_trans)
        self.update = QtWidgets.QPushButton(self.centralWidget)
        self.update.setObjectName("update")
        self.layout2.addWidget(self.update)
        self.delet = QtWidgets.QPushButton(self.centralWidget)
        self.delet.setObjectName("delet")
        self.layout2.addWidget(self.delet)
        self.layout3.addLayout(self.layout2)
        self.table = QtWidgets.QTableWidget(self.centralWidget)
        self.table.setMinimumSize(QtCore.QSize(500, 280))
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setAlternatingRowColors(True)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        item.setFont(font)
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(180)
        self.table.horizontalHeader().setMinimumSectionSize(35)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setDefaultSectionSize(40)
        self.table.verticalHeader().setMinimumSectionSize(35)
        self.layout3.addWidget(self.table)
        self.verticalLayout.addLayout(self.layout3)
        MWin.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MWin)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MWin.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MWin)
        self.statusBar.setObjectName("statusBar")
        MWin.setStatusBar(self.statusBar)
        self.actionimport = QtWidgets.QAction(MWin)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/import"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionimport.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.actionimport.setFont(font)
        self.actionimport.setObjectName("actionimport")
        self.actionexport = QtWidgets.QAction(MWin)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/export"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexport.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.actionexport.setFont(font)
        self.actionexport.setObjectName("actionexport")
        self.actionexit = QtWidgets.QAction(MWin)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionexit.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.actionexit.setFont(font)
        self.actionexit.setObjectName("actionexit")
        self.actionhelp = QtWidgets.QAction(MWin)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/help"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionhelp.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.actionhelp.setFont(font)
        self.actionhelp.setObjectName("actionhelp")
        self.actionabout = QtWidgets.QAction(MWin)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/about"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionabout.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.actionabout.setFont(font)
        self.actionabout.setObjectName("actionabout")
        self.actionconnect = QtWidgets.QAction(MWin)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/connect"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionconnect.setIcon(icon6)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.actionconnect.setFont(font)
        self.actionconnect.setObjectName("actionconnect")
        self.menuFile.addAction(self.actionimport)
        self.menuFile.addAction(self.actionexport)
        self.menuFile.addAction(self.actionconnect)
        self.menuFile.addAction(self.actionexit)
        self.menuAbout.addAction(self.actionhelp)
        self.menuAbout.addAction(self.actionabout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MWin)
        QtCore.QMetaObject.connectSlotsByName(MWin)

    def retranslateUi(self, MWin):
        _translate = QtCore.QCoreApplication.translate
        MWin.setWindowTitle(_translate("MWin", "Words Recorder 1.0"))
        self.input_origin_label.setText(_translate("MWin", "origin: "))
        self.insert.setText(_translate("MWin", "insert"))
        self.query.setText(_translate("MWin", "query"))
        self.input_trans_label.setText(_translate("MWin", "transl: "))
        self.update.setText(_translate("MWin", "update"))
        self.delet.setText(_translate("MWin", "delete"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MWin", "id"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MWin", "original words"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MWin", "translation"))
        self.menuFile.setTitle(_translate("MWin", "File"))
        self.menuAbout.setTitle(_translate("MWin", "About"))
        self.actionimport.setText(_translate("MWin", "import"))
        self.actionexport.setText(_translate("MWin", "export"))
        self.actionexit.setText(_translate("MWin", "exit"))
        self.actionhelp.setText(_translate("MWin", "help"))
        self.actionabout.setText(_translate("MWin", "about"))
        self.actionconnect.setText(_translate("MWin", "connect"))

import res_rc
