# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwin.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWin(object):
    def setupUi(self, MWin):
        MWin.setObjectName("MWin")
        MWin.resize(555, 600)
        MWin.setMinimumSize(QtCore.QSize(555, 0))
        MWin.setMaximumSize(QtCore.QSize(555, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWin.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MWin)
        self.centralwidget.setMinimumSize(QtCore.QSize(555, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.query = QtWidgets.QWidget()
        self.query.setObjectName("query")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.query)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.subLayout = QtWidgets.QVBoxLayout()
        self.subLayout.setSpacing(6)
        self.subLayout.setObjectName("subLayout")
        self.timeLabel = QtWidgets.QLabel(self.query)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeLabel.setFont(font)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.subLayout.addWidget(self.timeLabel)
        self.hintLabel = QtWidgets.QLabel(self.query)
        self.hintLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hintLabel.setWordWrap(False)
        self.hintLabel.setObjectName("hintLabel")
        self.subLayout.addWidget(self.hintLabel)
        self.groupBox = QtWidgets.QGroupBox(self.query)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layout1 = QtWidgets.QHBoxLayout()
        self.layout1.setSpacing(6)
        self.layout1.setObjectName("layout1")
        self.areaLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.areaLabel.setFont(font)
        self.areaLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.areaLabel.setObjectName("areaLabel")
        self.layout1.addWidget(self.areaLabel)
        self.areaBox = QtWidgets.QComboBox(self.groupBox)
        self.areaBox.setObjectName("areaBox")
        self.areaBox.addItem("")
        self.areaBox.addItem("")
        self.areaBox.addItem("")
        self.areaBox.addItem("")
        self.areaBox.addItem("")
        self.areaBox.addItem("")
        self.layout1.addWidget(self.areaBox)
        self.buildingLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buildingLabel.setFont(font)
        self.buildingLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.buildingLabel.setObjectName("buildingLabel")
        self.layout1.addWidget(self.buildingLabel)
        self.buildingBox = QtWidgets.QComboBox(self.groupBox)
        self.buildingBox.setObjectName("buildingBox")
        self.layout1.addWidget(self.buildingBox)
        self.layout1.setStretch(0, 1)
        self.layout1.setStretch(1, 3)
        self.layout1.setStretch(2, 1)
        self.layout1.setStretch(3, 3)
        self.verticalLayout_8.addLayout(self.layout1)
        self.layout2 = QtWidgets.QHBoxLayout()
        self.layout2.setSpacing(6)
        self.layout2.setObjectName("layout2")
        self.roomLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.roomLabel.setFont(font)
        self.roomLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roomLabel.setObjectName("roomLabel")
        self.layout2.addWidget(self.roomLabel)
        self.roomEdit = QtWidgets.QLineEdit(self.groupBox)
        self.roomEdit.setObjectName("roomEdit")
        self.layout2.addWidget(self.roomEdit)
        self.queryBtn = QtWidgets.QPushButton(self.groupBox)
        self.queryBtn.setObjectName("queryBtn")
        self.layout2.addWidget(self.queryBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.groupBox)
        self.cancelBtn.setObjectName("cancelBtn")
        self.layout2.addWidget(self.cancelBtn)
        self.help = QtWidgets.QPushButton(self.groupBox)
        self.help.setMaximumSize(QtCore.QSize(0, 16777215))
        self.help.setObjectName("help")
        self.layout2.addWidget(self.help)
        self.layout2.setStretch(0, 1)
        self.layout2.setStretch(1, 3)
        self.layout2.setStretch(2, 2)
        self.layout2.setStretch(3, 2)
        self.verticalLayout_8.addLayout(self.layout2)
        self.layout3 = QtWidgets.QHBoxLayout()
        self.layout3.setSpacing(6)
        self.layout3.setObjectName("layout3")
        self.checkLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkLabel.setFont(font)
        self.checkLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.checkLabel.setObjectName("checkLabel")
        self.layout3.addWidget(self.checkLabel)
        self.checkEdit = QtWidgets.QLineEdit(self.groupBox)
        self.checkEdit.setReadOnly(False)
        self.checkEdit.setObjectName("checkEdit")
        self.layout3.addWidget(self.checkEdit)
        self.leftLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftLabel.setFont(font)
        self.leftLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.leftLabel.setObjectName("leftLabel")
        self.layout3.addWidget(self.leftLabel)
        self.leftEdit = QtWidgets.QLineEdit(self.groupBox)
        self.leftEdit.setReadOnly(False)
        self.leftEdit.setObjectName("leftEdit")
        self.layout3.addWidget(self.leftEdit)
        self.layout3.setStretch(0, 1)
        self.layout3.setStretch(1, 3)
        self.layout3.setStretch(2, 1)
        self.layout3.setStretch(3, 3)
        self.verticalLayout_8.addLayout(self.layout3)
        self.layout4 = QtWidgets.QHBoxLayout()
        self.layout4.setSpacing(6)
        self.layout4.setObjectName("layout4")
        self.chargeTable = QtWidgets.QTextEdit(self.groupBox)
        self.chargeTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chargeTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chargeTable.setReadOnly(False)
        self.chargeTable.setObjectName("chargeTable")
        self.layout4.addWidget(self.chargeTable)
        self.verticalLayout_8.addLayout(self.layout4)
        self.subLayout.addWidget(self.groupBox)
        self.subLayout.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.subLayout)
        self.tabWidget.addTab(self.query, "")
        self.info = QtWidgets.QWidget()
        self.info.setObjectName("info")
        self.gridLayout = QtWidgets.QGridLayout(self.info)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.bugReportBox = QtWidgets.QGroupBox(self.info)
        self.bugReportBox.setObjectName("bugReportBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.bugReportBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout6 = QtWidgets.QHBoxLayout()
        self.layout6.setSpacing(6)
        self.layout6.setObjectName("layout6")
        self.githubLabel = QtWidgets.QLabel(self.bugReportBox)
        self.githubLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.githubLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.githubLabel.setObjectName("githubLabel")
        self.layout6.addWidget(self.githubLabel)
        self.githubEdit = QtWidgets.QLineEdit(self.bugReportBox)
        self.githubEdit.setMouseTracking(True)
        self.githubEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.githubEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.githubEdit.setObjectName("githubEdit")
        self.layout6.addWidget(self.githubEdit)
        self.layout6.setStretch(0, 1)
        self.layout6.setStretch(1, 6)
        self.verticalLayout.addLayout(self.layout6)
        self.layout7 = QtWidgets.QHBoxLayout()
        self.layout7.setSpacing(6)
        self.layout7.setObjectName("layout7")
        self.emailLabel = QtWidgets.QLabel(self.bugReportBox)
        self.emailLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.emailLabel.setObjectName("emailLabel")
        self.layout7.addWidget(self.emailLabel)
        self.emailEdit = QtWidgets.QLineEdit(self.bugReportBox)
        self.emailEdit.setMouseTracking(True)
        self.emailEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.emailEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.emailEdit.setObjectName("emailEdit")
        self.layout7.addWidget(self.emailEdit)
        self.layout7.setStretch(0, 1)
        self.layout7.setStretch(1, 6)
        self.verticalLayout.addLayout(self.layout7)
        self.gridLayout.addWidget(self.bugReportBox, 3, 0, 1, 1)
        self.offlineBox = QtWidgets.QGroupBox(self.info)
        self.offlineBox.setObjectName("offlineBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.offlineBox)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoLabel = QtWidgets.QLabel(self.offlineBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.infoLabel.setFont(font)
        self.infoLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.infoLabel.setObjectName("infoLabel")
        self.horizontalLayout.addWidget(self.infoLabel)
        self.gridLayout.addWidget(self.offlineBox, 0, 0, 1, 1)
        self.layout5 = QtWidgets.QHBoxLayout()
        self.layout5.setSpacing(6)
        self.layout5.setObjectName("layout5")
        self.onlineChargeLabel = QtWidgets.QLabel(self.info)
        self.onlineChargeLabel.setObjectName("onlineChargeLabel")
        self.layout5.addWidget(self.onlineChargeLabel)
        self.onlineChargeEdit = QtWidgets.QLineEdit(self.info)
        self.onlineChargeEdit.setMouseTracking(True)
        self.onlineChargeEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.onlineChargeEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.onlineChargeEdit.setObjectName("onlineChargeEdit")
        self.layout5.addWidget(self.onlineChargeEdit)
        self.gridLayout.addLayout(self.layout5, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.layout8 = QtWidgets.QHBoxLayout()
        self.layout8.setSpacing(6)
        self.layout8.setObjectName("layout8")
        self.onlineQueryLabel = QtWidgets.QLabel(self.info)
        self.onlineQueryLabel.setObjectName("onlineQueryLabel")
        self.layout8.addWidget(self.onlineQueryLabel)
        self.onlineQueryEdit = QtWidgets.QLineEdit(self.info)
        self.onlineQueryEdit.setMouseTracking(True)
        self.onlineQueryEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.onlineQueryEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.onlineQueryEdit.setObjectName("onlineQueryEdit")
        self.layout8.addWidget(self.onlineQueryEdit)
        self.gridLayout.addLayout(self.layout8, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.info)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{  \n"
"   color: rgba(0, 0, 0, 50%);\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.tabWidget.addTab(self.info, "")
        self.mainLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.mainLayout)
        MWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 26))
        self.menubar.setObjectName("menubar")
        MWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MWin)
        self.statusbar.setObjectName("statusbar")
        MWin.setStatusBar(self.statusbar)

        self.retranslateUi(MWin)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MWin)

    def retranslateUi(self, MWin):
        _translate = QtCore.QCoreApplication.translate
        MWin.setWindowTitle(_translate("MWin", "华科寝室用电查询系统 v1.0"))
        self.timeLabel.setText(_translate("MWin", "欢迎登陆本系统，今天是2017/8/28 15:12"))
        self.hintLabel.setText(_translate("MWin", "操作：请依次选择区域、楼栋、房间，点查询完成查询操作！"))
        self.groupBox.setTitle(_translate("MWin", "( ・◇・)？"))
        self.areaLabel.setText(_translate("MWin", "区域："))
        self.areaBox.setItemText(0, _translate("MWin", "-请选择-"))
        self.areaBox.setItemText(1, _translate("MWin", "东区"))
        self.areaBox.setItemText(2, _translate("MWin", "留学生楼"))
        self.areaBox.setItemText(3, _translate("MWin", "西区"))
        self.areaBox.setItemText(4, _translate("MWin", "韵苑"))
        self.areaBox.setItemText(5, _translate("MWin", "紫菘"))
        self.buildingLabel.setText(_translate("MWin", "楼号："))
        self.roomLabel.setText(_translate("MWin", "房间："))
        self.queryBtn.setText(_translate("MWin", "查询"))
        self.cancelBtn.setText(_translate("MWin", "取消"))
        self.help.setText(_translate("MWin", " "))
        self.checkLabel.setText(_translate("MWin", "抄表时间："))
        self.leftLabel.setText(_translate("MWin", "剩余电量："))
        self.chargeTable.setPlaceholderText(_translate("MWin", "Ctrl+h 获取帮助"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.query), _translate("MWin", "电费查询"))
        self.bugReportBox.setTitle(_translate("MWin", "bug反馈"))
        self.githubLabel.setText(_translate("MWin", "GitHub: "))
        self.githubEdit.setText(_translate("MWin", "https://github.com/LewisTian/PyQt5-Apps"))
        self.emailLabel.setText(_translate("MWin", "Email: "))
        self.emailEdit.setText(_translate("MWin", "lewissmith@126.com"))
        self.offlineBox.setTitle(_translate("MWin", "上班时间：每日17点至22点（节假日另见充值点通知）"))
        self.infoLabel.setText(_translate("MWin", "      紫菘二栋充值点： 每周一、二、四、五、日    \n"
"      西八舍充值点：    每周一、二、三、五、六   \n"
"      东八舍充值点：    每周一、三、四、五、六    \n"
"      韵苑五栋充值点： 每周一、三、四、五、六\n"
"      韵苑21栋充值点：每周一、二、四、五、日"))
        self.onlineChargeLabel.setText(_translate("MWin", "在线充值："))
        self.onlineChargeEdit.setText(_translate("MWin", "http://sdhq.hust.edu.cn/ICBS/mobileweb/html/index.html"))
        self.onlineQueryLabel.setText(_translate("MWin", "在线查询："))
        self.onlineQueryEdit.setText(_translate("MWin", "http://202.114.18.218/Main.aspx"))
        self.label.setText(_translate("MWin", "—— 我是有底线的 ——"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.info), _translate("MWin", "关于"))

import res_rc
