# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mwin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWin(object):
    def setupUi(self, MWin):
        MWin.setObjectName("MWin")
        MWin.resize(600, 350)
        MWin.setMinimumSize(QtCore.QSize(400, 350))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        MWin.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/cat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MWin.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MWin)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingGroup = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.settingGroup.setFont(font)
        self.settingGroup.setObjectName("settingGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingGroup)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.banner_image = QtWidgets.QLabel(self.settingGroup)
        self.banner_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.banner_image.setObjectName("banner_image")
        self.horizontalLayout_3.addWidget(self.banner_image)
        self.banner_image_btn = QtWidgets.QToolButton(self.settingGroup)
        self.banner_image_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.banner_image_btn.setObjectName("banner_image_btn")
        self.horizontalLayout_3.addWidget(self.banner_image_btn)
        self.horizontalLayout_3.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.background_color = QtWidgets.QLabel(self.settingGroup)
        self.background_color.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.background_color.setObjectName("background_color")
        self.horizontalLayout_4.addWidget(self.background_color)
        self.background_color_btn = QtWidgets.QToolButton(self.settingGroup)
        self.background_color_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.background_color_btn.setObjectName("background_color_btn")
        self.horizontalLayout_4.addWidget(self.background_color_btn)
        self.horizontalLayout_4.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.font = QtWidgets.QLabel(self.settingGroup)
        self.font.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.font.setObjectName("font")
        self.horizontalLayout_5.addWidget(self.font)
        self.font_btn = QtWidgets.QToolButton(self.settingGroup)
        self.font_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.font_btn.setObjectName("font_btn")
        self.horizontalLayout_5.addWidget(self.font_btn)
        self.horizontalLayout_5.setStretch(0, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.settingGroup)
        self.btnGroup = QtWidgets.QGroupBox(self.tab)
        self.btnGroup.setMinimumSize(QtCore.QSize(0, 80))
        self.btnGroup.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnGroup.setFont(font)
        self.btnGroup.setObjectName("btnGroup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.btnGroup)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.btnGroup)
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/cat.png"))
        self.label.setScaledContents(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(363, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.start_btn = QtWidgets.QToolButton(self.btnGroup)
        self.start_btn.setMinimumSize(QtCore.QSize(65, 0))
        self.start_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_2.addWidget(self.start_btn)
        self.open_btn = QtWidgets.QToolButton(self.btnGroup)
        self.open_btn.setMinimumSize(QtCore.QSize(65, 0))
        self.open_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_btn.setObjectName("open_btn")
        self.horizontalLayout_2.addWidget(self.open_btn)
        self.verticalLayout.addWidget(self.btnGroup)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MWin.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MWin)
        self.statusBar.setObjectName("statusBar")
        MWin.setStatusBar(self.statusBar)

        self.retranslateUi(MWin)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MWin)

    def retranslateUi(self, MWin):
        _translate = QtCore.QCoreApplication.translate
        MWin.setWindowTitle(_translate("MWin", "Cat Calendar"))
        self.settingGroup.setTitle(_translate("MWin", "General Settings"))
        self.banner_image.setText(_translate("MWin", "Banner image (1: 1): default.png"))
        self.banner_image_btn.setText(_translate("MWin", "..."))
        self.background_color.setText(_translate("MWin", "Background color: #f0f0f0"))
        self.background_color_btn.setText(_translate("MWin", "..."))
        self.font.setText(_translate("MWin", "Font: Microsoft YaHei Mono"))
        self.font_btn.setText(_translate("MWin", "..."))
        self.btnGroup.setTitle(_translate("MWin", "Buttons"))
        self.label.setToolTip(_translate("MWin", "Cat Calendar, mewo~"))
        self.start_btn.setText(_translate("MWin", "Start"))
        self.start_btn.setShortcut(_translate("MWin", "Ctrl+Return"))
        self.open_btn.setText(_translate("MWin", "Open"))
        self.open_btn.setShortcut(_translate("MWin", "Ctrl+O"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MWin", "Home"))
        self.plainTextEdit.setPlainText(_translate("MWin", "A simple Cat Calendar image generator that uses the \"www.dutangapp.cn\" and \"wufazhuce.com\" api.\n"
"\n"
"github.com/LewisTian/PyQt5-Apps"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MWin", "About"))

import res_rc
